-- Optional: seed the frozen MVP puzzle into Supabase/Postgres.
-- Apply 001_init.sql first. The play API currently uses in-memory storage by default;
-- switch to Postgres in a later step.

insert into daily_puzzles (
  id,
  puzzle_date,
  graph_version,
  start_article_id,
  target_article_id,
  nodes,
  edges,
  optimal_path,
  optimal_length,
  difficulty,
  generator_seed,
  corpus_version
) values (
  '11111111-1111-1111-1111-111111111111',
  current_date,
  to_char(current_date, 'YYYY-MM-DD') || '.seed',
  'Albert_Einstein',
  'Nintendo',
  '[
    {"id":"Albert_Einstein","title":"Albert Einstein","x":0.12,"y":0.48,"kind":"start"},
    {"id":"Physics","title":"Physics","x":0.32,"y":0.28,"kind":"normal"},
    {"id":"Mathematics","title":"Mathematics","x":0.55,"y":0.35,"kind":"normal"},
    {"id":"Nintendo","title":"Nintendo","x":0.88,"y":0.52,"kind":"target"},
    {"id":"Germany","title":"Germany","x":0.22,"y":0.72,"kind":"normal"},
    {"id":"Japan","title":"Japan","x":0.62,"y":0.78,"kind":"normal"},
    {"id":"Relativity","title":"Relativity","x":0.28,"y":0.12,"kind":"normal"},
    {"id":"Quantum_mechanics","title":"Quantum mechanics","x":0.45,"y":0.15,"kind":"normal"},
    {"id":"Geometry","title":"Geometry","x":0.58,"y":0.18,"kind":"normal"},
    {"id":"Science","title":"Science","x":0.40,"y":0.48,"kind":"normal"},
    {"id":"Computer_science","title":"Computer science","x":0.68,"y":0.42,"kind":"normal"},
    {"id":"Video_game","title":"Video game","x":0.78,"y":0.30,"kind":"normal"},
    {"id":"Berlin","title":"Berlin","x":0.10,"y":0.85,"kind":"normal"},
    {"id":"Kyoto","title":"Kyoto","x":0.72,"y":0.90,"kind":"normal"},
    {"id":"Shigeru_Miyamoto","title":"Shigeru Miyamoto","x":0.90,"y":0.70,"kind":"normal"},
    {"id":"Philosophy","title":"Philosophy","x":0.48,"y":0.62,"kind":"normal"}
  ]'::jsonb,
  '[
    {"from":"Albert_Einstein","to":"Physics"},
    {"from":"Albert_Einstein","to":"Relativity"},
    {"from":"Albert_Einstein","to":"Germany"},
    {"from":"Albert_Einstein","to":"Science"},
    {"from":"Physics","to":"Mathematics"},
    {"from":"Physics","to":"Quantum_mechanics"},
    {"from":"Physics","to":"Relativity"},
    {"from":"Physics","to":"Science"},
    {"from":"Mathematics","to":"Geometry"},
    {"from":"Mathematics","to":"Computer_science"},
    {"from":"Mathematics","to":"Nintendo"},
    {"from":"Germany","to":"Berlin"},
    {"from":"Germany","to":"Japan"},
    {"from":"Japan","to":"Kyoto"},
    {"from":"Japan","to":"Nintendo"},
    {"from":"Relativity","to":"Physics"},
    {"from":"Quantum_mechanics","to":"Physics"},
    {"from":"Science","to":"Physics"},
    {"from":"Science","to":"Mathematics"},
    {"from":"Science","to":"Philosophy"},
    {"from":"Computer_science","to":"Mathematics"},
    {"from":"Computer_science","to":"Video_game"},
    {"from":"Video_game","to":"Nintendo"},
    {"from":"Video_game","to":"Shigeru_Miyamoto"},
    {"from":"Shigeru_Miyamoto","to":"Nintendo"},
    {"from":"Geometry","to":"Mathematics"},
    {"from":"Berlin","to":"Germany"},
    {"from":"Kyoto","to":"Japan"},
    {"from":"Philosophy","to":"Science"},
    {"from":"Nintendo","to":"Video_game"}
  ]'::jsonb,
  '["Albert_Einstein","Physics","Mathematics","Nintendo"]'::jsonb,
  3,
  '{"note":"hand-authored seed"}'::jsonb,
  'seed-mvp-v1',
  'hand-authored-mvp'
)
on conflict (puzzle_date) do nothing;
